// Code generated by protoc-gen-go. DO NOT EDIT.
// source: internal/api/api.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type OnEventRequest struct {
	Buffer               []byte   `protobuf:"bytes,1,opt,name=buffer,proto3" json:"buffer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OnEventRequest) Reset()         { *m = OnEventRequest{} }
func (m *OnEventRequest) String() string { return proto.CompactTextString(m) }
func (*OnEventRequest) ProtoMessage()    {}
func (*OnEventRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_52fff2e9b74eb1d1, []int{0}
}

func (m *OnEventRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnEventRequest.Unmarshal(m, b)
}
func (m *OnEventRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnEventRequest.Marshal(b, m, deterministic)
}
func (m *OnEventRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnEventRequest.Merge(m, src)
}
func (m *OnEventRequest) XXX_Size() int {
	return xxx_messageInfo_OnEventRequest.Size(m)
}
func (m *OnEventRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OnEventRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OnEventRequest proto.InternalMessageInfo

func (m *OnEventRequest) GetBuffer() []byte {
	if m != nil {
		return m.Buffer
	}
	return nil
}

type OnEventResponse struct {
	Buffer               []byte   `protobuf:"bytes,1,opt,name=buffer,proto3" json:"buffer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OnEventResponse) Reset()         { *m = OnEventResponse{} }
func (m *OnEventResponse) String() string { return proto.CompactTextString(m) }
func (*OnEventResponse) ProtoMessage()    {}
func (*OnEventResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_52fff2e9b74eb1d1, []int{1}
}

func (m *OnEventResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnEventResponse.Unmarshal(m, b)
}
func (m *OnEventResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnEventResponse.Marshal(b, m, deterministic)
}
func (m *OnEventResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnEventResponse.Merge(m, src)
}
func (m *OnEventResponse) XXX_Size() int {
	return xxx_messageInfo_OnEventResponse.Size(m)
}
func (m *OnEventResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OnEventResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OnEventResponse proto.InternalMessageInfo

func (m *OnEventResponse) GetBuffer() []byte {
	if m != nil {
		return m.Buffer
	}
	return nil
}

func init() {
	proto.RegisterType((*OnEventRequest)(nil), "ptyrpc.OnEventRequest")
	proto.RegisterType((*OnEventResponse)(nil), "ptyrpc.OnEventResponse")
}

func init() { proto.RegisterFile("internal/api/api.proto", fileDescriptor_52fff2e9b74eb1d1) }

var fileDescriptor_52fff2e9b74eb1d1 = []byte{
	// 178 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xcb, 0xcc, 0x2b, 0x49,
	0x2d, 0xca, 0x4b, 0xcc, 0xd1, 0x4f, 0x2c, 0xc8, 0x04, 0x61, 0xbd, 0x82, 0xa2, 0xfc, 0x92, 0x7c,
	0x21, 0xb6, 0x82, 0x92, 0xca, 0xa2, 0x82, 0x64, 0x25, 0x0d, 0x2e, 0x3e, 0xff, 0x3c, 0xd7, 0xb2,
	0xd4, 0xbc, 0x92, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x21, 0x31, 0x2e, 0xb6, 0xa4, 0xd2,
	0xb4, 0xb4, 0xd4, 0x22, 0x09, 0x46, 0x05, 0x46, 0x0d, 0x9e, 0x20, 0x28, 0x4f, 0x49, 0x93, 0x8b,
	0x1f, 0xae, 0xb2, 0xb8, 0x20, 0x3f, 0xaf, 0x38, 0x15, 0x97, 0x52, 0x23, 0x3f, 0x2e, 0xae, 0x80,
	0x92, 0xca, 0xe0, 0xd4, 0xa2, 0xb2, 0xcc, 0xe4, 0x54, 0x21, 0x07, 0x2e, 0x76, 0xa8, 0x46, 0x21,
	0x31, 0x3d, 0x88, 0xb5, 0x7a, 0xa8, 0x76, 0x4a, 0x89, 0x63, 0x88, 0x43, 0x6c, 0x50, 0x62, 0xd0,
	0x60, 0x34, 0x60, 0x74, 0x52, 0x8f, 0x52, 0x4d, 0xcf, 0x2c, 0xc9, 0x28, 0x4d, 0xd2, 0x4b, 0xce,
	0xcf, 0xd5, 0xcf, 0x2a, 0xcd, 0xc9, 0x34, 0xc9, 0xd3, 0x87, 0xe8, 0xd0, 0x47, 0xf6, 0x5f, 0x12,
	0x1b, 0xd8, 0x73, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x06, 0x6d, 0x93, 0x83, 0xf6, 0x00,
	0x00, 0x00,
}
